number1 = int(input("Введите первое число: "))
number2 = int(input("Введите второе число: "))
print("Результат сложения: ", number1 + number2)
print("Результат вычитания: ", number1 - number2)
print("Результат умножения: ", number1 * number2)
print("Результат деления: ", number1 / number2)
print("Результат возведения в степь: ", number1 ** number2)
print("Результат деления с целым остатком: ", number1 // number2)
print("Результат остатка от деления: ", number1 % number2)